on:
  push:
    branches:
      main
  schedule:
    - cron: '0 0 * * 0'
name: Render
jobs:
  bookdown:
    name: Render-Solutions
    runs-on: ubuntu-latest
    container: geocompr/geocompr:suggests
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render Book
        run: |
          Rscript -e 'remotes::install_github("geocompr/geocompkg", dependencies = TRUE, force = TRUE)'
          Rscript -e 'library(terra)'
          Rscript -e 'bookdown::render_book("index.Rmd")'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          destination_dir: solutions
          publish_branch: gh-pages
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
